---
title: "Biochemistry R training"
subtitle: "Session 1: Overview, R/RStudio, data organistaion & import"
author: "Mik Black<BR>Department of Biochemistry"
date: "22 February 2016"
output: ioslides_presentation
---

## Overview - workshop

URL: https://github.com/mikblacklab/Biochem_R_training

 - Monday Session 1 - 9:30am-12:30pm (Mik/James)
     - R/RStudio overview
     - Data organisation & import 
 - Monday Session 2 - 1:30pm-4:30pm (Murray/Tom) 
     - Introduction to R 
 - Tuesday Session 3 - 9:30am-12:30pm (Murray/Elizabeth)
     - Data manipulation & visualisation 
 - Tuesday Session 4 - 1:30pm-4:30pm (Mik/James)
     - Reproducible research with Rmarkdown

## Overview - session 1

 - Why are you here?
 - Introductions 
     - instructors
     - material 
     - each other
 - Etherpad
 - Introducing R & RStudio
 - Data organisation (James)
 - Importing data into R (James)

## Why are you here?

 - Reason 1: we are offering a workshop
 - Reason 2: you think you need to know the things we are teaching
 - Motivation behind both:
     - our discplines are becoming much more "data-centric"
     - relevant analytic tools are always evolving, so are not available in canned, 
     easy-to-use software applications
     - there is movement internationally towards increasing the "digital literacy" of
     early-career researchers through formal training workshops outside the current 
     academic curriculum.

## Introductions: instructors 

In order of appearance:

 - Mik Black
 - James Boocock 
 - Murray Cadzow 
 - Tom Kelly 
 - Elizabeth Permina
 
## Introductions: the material

 - We will be teaching you very basic concepts in data organisation, manipulation and visualisation
 - We are using the R language, which we interact with through the RStudio interface
 - Some of the material we are using has come from the following sources:
    - Data Carperntry: http://www.datacarpentry.org/
    - Software Carpentry: http://software-carpentry.org/
 - Both of the above sites are excellent sources of information if you are looking to improve your ability to perform basic data analysis, or get more into programmming.

## Introductions: each other

 - Show of hands
     - where are people from?
     - what are you working on?
 - Have a chat to your neighbours
 
## Etherpad

 - Etherpad is a tool from Mozilla that allows real-time collaborative document 
 editing within a browser.
     - [Workshop Etherpad link](https://public.etherpad-mozilla.org/p/2016-02-22_Otago_Biochem)
 - We can use Etherpad during the workshop for lots of things:
     - collecting attendence info
     - taking notes
     - asking questions
     - sending information
 - You can set up your own Etherpad (note that anyone with the link can see it) via Mozilla:
     - https://public.etherpad-mozilla.org/

## Introducing R

## Introducing RStudio
